//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Echo.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("halmbimoannfadoedalghfeihhjblaaj")]
        public string ExtensionId {
            get {
                return ((string)(this["ExtensionId"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0RGsdeT8tzSW9WOT6L5YP6lgHp3jUZbPI4CoyL8KraNBnKFkufBc4jz1SFbDcFynMQPijvnO785eDzHfKReIRQiFCOF7J5WeLjFzCbVnX0cPTiocnOGVc5EWUzCq8rxiOuprZwPS4LZaUWwjPnnW3ssx2TLm6jk3554P6l0bf9HUGMS9z7v4FCIKa+o0x5aeyfJHV+WRWR5eOMzYjQxdHki4JkIEoAjwLfFqUiA3yBy6L7//UO5KDO4i/fx9dgTZbWOhArCTgSiajsXIfXJ3kq20HEBpkROkmIRUOVoM0dp4wbgh8EMrQ/nTYAwNWSkGRKvr6lwuyS45onjxuMPWQwIDAQAB")]
        public string ExtensionKey {
            get {
                return ((string)(this["ExtensionKey"]));
            }
            set {
                this["ExtensionKey"] = value;
            }
        }
    }
}
