//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelayedEcho.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("kndkemaambgolcpdpfllbhmllkdfkfno")]
        public string ExtensionId {
            get {
                return ((string)(this["ExtensionId"]));
            }
            set {
                this["ExtensionId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA9tyrsYPAy3TSnF15kETYe/5j/ghfkqTH+MHaX06waG1w2ho/LAvurqfgH2uWN2W/u4izUHWKMF6PHl3yhcIAuDerINbgBZ5nBKEtgl5byG9+Mc5mBDK50gai53cdhXW9A4WKn3mIY5AhSafztWXoS7qEqrDjhVGkuuaCYkRPXsZNUVyyrxdniIKARc6kLXGK8ztKQOU3NOlJv4CjrZ2rboTlGj2HhFgsjG3Q7JuQJ+X5H82048HUM0dRiB32g8fXpYngIaE+W9hU/TGt8TyzQ9jg1TZ+5U7YZRrBeNMWFG3/YG5XODuZ1hnScYN5ARglcnf5Y7oq89OpXX0gqhZ3IwIDAQAB")]
        public string ExtensionKey {
            get {
                return ((string)(this["ExtensionKey"]));
            }
            set {
                this["ExtensionKey"] = value;
            }
        }
    }
}
